### ISSUE TITLE
Osteotomy(Cutting) Planes

### ISSUE THREAD

**Issue by cmfsx** [lassoan/SlicerBoneReconstructionPlanner#6] opened 2020-12-05 09:20 UTC
There are two kinds of osteotomy planes for the mandible.  There is no standard or conventional names to name them but for explanation I would name them as following. 

1. Mandibular resection planes 
    This will always be two planes. always the first and the last plane. 

![1](https://user-images.githubusercontent.com/57766971/101238791-d3de4480-36e2-11eb-923e-7d3b1761b226.png)

2. Fibula segment planes

This will be marked as one plane by the surgeon (this  if possible should be taken by the point of the curve markup) and the software will need to calculate the second plane based on that so that the fibula can be physically shaped. 

Depending on the number of "bone segments" needed for the reconstruction the number can vary. 

In the simplest reconstruction with just one "bone segment", this plane would not be necessary. 

Then if two "bone segments" are needed then one of these planes like ilustrated. then with each additioanle "bone segment (n)" this will increase (n-1) number of fibula segments will be need. 

Here we will need in addition to the plane marked by the surgeon (P3), P4 and another P5 plane would be needed on the Fibula. 

![2](https://user-images.githubusercontent.com/57766971/101238794-db055280-36e2-11eb-886f-1a21ea9a651c.png)

**Comment by mauigna06** [comment] 2020-12-05 10:45
Yes. I have thought a little about this and your explanation comes in hand. I'd like to set up a dynamic GUI so that the cutting plane selectors can be created based on the number of bone segments selected on a ComboBox. After the planes are selected in the selectors a click on an apply button would create all the fibula planes over the fibula line with the corresponding transform so they are in the right position. It may take some time to do this because I have never set up a dynamic GUI and I have to add the planes to a list that I would apply a list of transforms to and I think is kinda hard

**Comment by lassoan** [comment] 2020-12-05 16:01
I would recommend to organize data in subject hierarchy folders. For example, one folder for mandible cutting planes, another folder for the automatically generated fibula cutting planes, etc.

In the module, you can add a subject hierarchy tree widget that shows all the nodes that are in one folder, thereby avoiding the need to create a dynamic GUI manually. You can use that to select existing planes for editing or remove them.

I would not add a combobox for predefining number of mandible cutting planes, you can just have buttons for adding/removing a plane.

**Comment by cmfsx** [comment] 2020-12-05 17:27
@lassoan  and @mauigna06  I am just thinking, don't we already have enough information to generate the cutting planes? Once we define the resection planes at two ends, with the mandibular curve markup we define each segment ends (fiducial points). Then based on the angle can't we calculate the two planes we need to cut the bone?  I don't think we need any more information to make the cutting planes. This GUI is good as it is. But the calculation part will have to be programmed. 

@mauigna06 if this is not clear I can come to zoom. 

![3](https://user-images.githubusercontent.com/57766971/101259098-16297500-3727-11eb-8111-d547800d8281.png)

![Screenshot from 2020-12-05 18-13-51](https://user-images.githubusercontent.com/57766971/101259143-5b4da700-3727-11eb-8a13-4c942602b70b.png)

**Comment by lassoan** [comment] 2020-12-05 17:37
Yes, mandible cutting planes fully define fibula cutting planes, we just need to specify the fibula line, fibula backplane orientation (or use a plane to define both), starting point along the fibula line, and small offsets between segments.

**Comment by mauigna06** [comment] 2020-12-05 19:02
I'll explore how the qMRMLSubjectHierarchyTreeView works and I'll add it to the GUI so folders with the planes can be shown inside them. 
Then I'll try to set up the fibula planes and their corresponding transforms iterating though a list. 
Also I'll try to make interaction handles appear by default. 
These changes may take me a couple of days because I'm studying also.

**Comment by mauigna06** [comment] 2020-12-07 13:34
I investigated inside the classes: qSlicerMarkupsPlaceWidget, qSlicerMarkupsModuleWidget, vtkSlicerMarkupsLogic, vtkMRMLInteractionNode, vtkMRMLMarkupsPlaneNode, vtkMRMLSubjectHierarchyNode

And I haven't found how to create the planes nodes inside a folder by default with starting name myPlane through the qSlicerMarkupsPlaceWidget
I'd like the created planes to be shown in the qMRMLSubjectHierarchyTreeView like this:
```
myFolder/myPlane_1
myFolder/myPlane_2
myFolder/myPlane_3
myFolder/myPlane_4
```

(I know how to move a plane inside a folder after it has been created)
```
shNode = slicer.mrmlScene.GetSubjectHierarchyNode()
shNode.CreateFolderItem(sceneItemID,"MyFolder")
mID = shNode.GetItemByName("myFolder")
shNode.CreateItem(mID,planeNode) #planeNode is moved to myFolder
```

**Comment by lassoan** [comment] 2020-12-08 01:47
> And I haven't found how to create the planes nodes inside a folder by default with starting name myPlane through the qSlicerMarkupsPlaceWidget

There is no function that does everything like this "by default". You implement it yourself: add an "Add cut plane" button, when the user clicks on it then you create the markups plane node, set its name, subject hierarchy parent, add an observer, etc.

When the user places a point of the plane then the observer will call your callback function. In that function you can set the plane orientation, hide control points & show interaction arrows (if there is at least one placed control point), update the corresponding fibula plane's position and orientation, etc.

**Comment by mauigna06** [comment] 2020-12-08 14:49
I haven't thought about it that way. Thank you Andras. I was able to make it work. I just have to update the transforms when mandibular planes are modified. I will do that on the following days.

**Comment by mauigna06** [comment] 2020-12-10 15:01
In the [last commit](https://github.com/lassoan/SlicerBoneReconstructionPlanner/commit/85f27db4e35248f0cc031d9e028b66801ee2afab) you can create any number of mandibular planes and the fibula planes with its transforms will be created. 
A little problem is that the fibula planes are too small to visualize them properly. I don't know how to resize them

**Comment by lassoan** [comment] 2020-12-11 13:54
I've updated the Design.pptx slide with the cutting plane angles (now it is editable in the pptx):

![image](https://user-images.githubusercontent.com/307929/101910352-cb778500-3b8c-11eb-92df-2c894d8f416c.png)

A few things to note:
- User has complete freedom in choosing first and last mandible plane angle
- There is very little freedom in choosing all other mandible plane angles, because if mandible plane 2 does not half the angle between bone segment 1 and bone segment 2 then there is a mismatch in cross-section area (as you move away from half angle, one of the cross-section is getting smaller, the other is getting larger)
- It is not enough to reproduce the total "Segment angle" rotation between bone segments but we need to reproduce the two rotation angle components (rotation along MandiblePlainStraight x and y axes)
- A small space must be added between origin of FibulaPlane1B and FibulaPlane2A. It can be determined by getting the two plane/segmentation intersections (using vtkCutter), transform it to the fibula coordinate system (vtkTransform), get the two bounding boxes (polydata->GetBounds()), the overlap of z coordinate range tells how much space must be added to avoid overlap.

**Comment by lassoan** [comment] 2020-12-12 05:49
> A little problem is that the fibula planes are too small to visualize them properly. I don't know how to resize them

Plane extent along its x and y axes are determined by the second and third control positions (first control position is the origin, second is the endpoint of its x axis, third one determines the plane orientation and extent along the y axis).

**Comment by cmfsx** [comment] 2020-12-12 12:48
> first control position is the origin, second is the endpoint of its x axis, third one determines the plane orientation and extent along the y axis

I have left out all the problems I have associated with plane markup as I believe it is been revamp by Kyle Sunderland
 and Rafael Palomar and hoping when they improve it automatically it will improve the functionality here.

**Comment by lassoan** [comment] 2020-12-12 17:52
It could be useful if you could add a separate issue here for markups plane improvements that you would like to see, just to make sure that we are aware of what you have in mind.

**Comment by mauigna06** [comment] 2020-12-12 19:45
I think I have found the right formula to transform the mandible planes to fibula planes as it was desired (contact surface area maximazed) and specified on the picture. I have it on paper. 
![101910352-cb778500-3b8c-11eb-92df-2c894d8f416c](https://user-images.githubusercontent.com/19158307/101993145-1bdb0980-3c97-11eb-95c1-a311df9ad39e.png)
I'll program it when I have some time because I have to edit the previous version because I have to make some angle checks to make sure the transforms are set up properly.

---------------

> It is not enough to reproduce the total "Segment angle" rotation between bone segments but we need to reproduce the two rotation angle components (rotation along MandiblePlainStraight x and y axes)

Let me reference to this picture:
![mandibule2fibula__](https://user-images.githubusercontent.com/19158307/101993284-0f0ae580-3c98-11eb-9f41-7adea66c9708.png)

Till now we have a MandiblePlane2FibulaPlane transform. @lassoan, are you saying that you also want a MandiblePlane2MandiblePlaneStraight transform?

**Comment by lassoan** [comment] 2020-12-12 19:57
MandiblePlane2MandiblePlaneStraight will be needed when we implement automatic plane placement from a single point. We will determine MandiblePlaneStraight plane from the centerline and the user-defined point and set MandiblePlane2MandiblePlaneStraight to a slight rotation by default. The user will then just need to  do small adjustments (if anything).

**Comment by cmfsx** [comment] 2020-12-12 23:23
I found this video which will give an idea about how this is done. Right now our calculations are spot on but I thought this might help you to gain a better insight!

**Comment by mauigna06** [comment] 2020-12-13 10:22
Thank you Manjula. The videos were useful in understanding the surgical process

**Comment by mauigna06** [comment] 2020-12-13 13:42
I have updated the transforms to match the required positioning of the fibula planes. I'll close the issue

**Closed by mauigna06** 2020-12-13 13:42 UTC
